{{ edit_comment_prod }}

{% if 'supervisord' == php_type %}
FROM wayofdev/php-base:{{ php_version }}-cli-{{ os_name }}-latest
{% else %}
FROM wayofdev/php-base:{{ php_version }}-{{ php_type }}-{{ os_name }}-latest
{% endif %}

# Labels
# https://github.com/opencontainers/image-spec/blob/main/annotations.md
LABEL "maintainer"="lotyp <lotyp7@gmail.com>"
LABEL "vendor"="wayofdev"
LABEL "org.opencontainers.image.authors"="lotyp <lotyp7@gmail.com>"
LABEL "org.opencontainers.image.url"="https://hub.docker.com/r/wayofdev/php-{{ level }}"
LABEL "org.opencontainers.image.documentation"="https://github.com/wayofdev/docker-php-{{ level }}"
LABEL "org.opencontainers.image.source"="https://github.com/wayofdev/docker-php-{{ level }}"
LABEL "org.opencontainers.image.vendor"="wayofdev"
LABEL "org.opencontainers.image.licenses"="MIT"
LABEL "org.opencontainers.image.ref.name"="{{ php_version }}-{{ level }}"
LABEL "org.opencontainers.image.title"="PHP-{{ php_type|upper }} {{ php_version }}-{{ level }}"
LABEL "org.opencontainers.image.description"="PHP-{{ php_type|upper }} {{ php_version }}-{{ level }}"

RUN set -eux; \
    rm -rf /var/cache/apk/* \
    && rm -rf /tmp/* \
    && apk -U upgrade -a \
    # Add production dependencies
{% if 'supervisord' == php_type %}
    && apk add --no-cache supervisor \
{% endif %}
    # Temporary build dependencies for compiling Pecl extensions
    && apk add --no-cache --virtual .temp-build-deps \
        $PHPIZE_DEPS \
    # Soap Messaging Protocol
{% if 'soap' in ext_native_enabled %}
    && apk add --no-cache libxml2-dev \
    && docker-php-ext-install -j$(nproc) soap \
    && apk del libxml2-dev \
{% endif %}
    ### Image Processing
    # https://www.php.net/manual/en/refs.utilspec.image.php
    # Exif - (Exchangeable image information) / Image Meta Data
{% if 'exif' in ext_native_enabled %}
    && docker-php-ext-install -j$(nproc) exif \
{% endif %}
    # GD
{% if 'gd' in ext_native_enabled %}
    && apk add --no-cache \
        freetype libjpeg-turbo libpng libxpm libwebp \
        freetype-dev libjpeg-turbo-dev libpng-dev libxpm-dev libwebp-dev \
    && docker-php-ext-configure gd --enable-gd --with-webp --with-jpeg --with-xpm --with-freetype \
    && docker-php-ext-install -j$(nproc) gd \
    && apk del freetype-dev libjpeg-turbo-dev libpng-dev libxpm-dev libwebp-dev \
{% endif %}
    ####################################################################################################################
    # Pecl Dependencies
    # Imagick
{% if 'imagick' in ext_pecl_enabled %}
    && apk add --no-cache \
        imagemagick libgomp \
        imagemagick-dev \
    && pecl install imagick-{{ ext_pecl_versions.imagick }} \
    && docker-php-ext-enable imagick \
    && apk del imagemagick-dev \
{% endif %}
    # Client for Apache Kafka
{% if 'rdkafka' in ext_pecl_enabled %}
    && apk add --no-cache \
        librdkafka \
        librdkafka-dev \
    && pecl install rdkafka-{{ ext_pecl_versions.rdkafka }} \
    && docker-php-ext-enable rdkafka \
    && apk del librdkafka-dev \
{% endif %}
    # AMQP - Communicate with any amqp compliant server
{% if 'amqp' in ext_pecl_enabled %}
    && apk add --no-cache \
        rabbitmq-c \
        rabbitmq-c-dev \
    && pecl install amqp-{{ ext_pecl_versions.amqp }} \
    && docker-php-ext-enable amqp \
    && apk del rabbitmq-c-dev \
{% endif %}
    # Protobuf - Google's extensible mechanism for serializing structured data.
    # https://spiral.dev/docs/grpc-configuration#toolkit-installation-install-protobuf-extension-optional
{% if 'protobuf' in ext_pecl_enabled %}
    && pecl install protobuf-{{ ext_pecl_versions.protobuf }} \
    && docker-php-ext-enable --ini-name docker-php-ext-10-protobuf.ini protobuf \
{% endif %}
    # Yaml parser and emitter
{% if 'yaml' in ext_pecl_enabled %}
    && apk add --no-cache \
        yaml \
        yaml-dev \
    && pecl install yaml-{{ ext_pecl_versions.yaml }} \
    && docker-php-ext-enable yaml \
    && apk del yaml-dev \
{% endif %}
    && apk del -f .temp-build-deps \
    && rm -rf /var/www/html \
    && mkdir /app \
    && chown www-data:www-data /app

{% if 'fpm' == php_type %}
COPY ./configs/php-fpm.d/ /usr/local/etc/php-fpm.d/
{% endif %}
{% if 'supervisord' == php_type %}
COPY --chown=www-data ./configs/supervisord.conf /etc/supervisord.conf
{% endif %}

WORKDIR /app

USER www-data

{% if 'supervisord' == php_type %}
CMD ["/usr/bin/supervisord", "-c", "/etc/supervisord.conf"]
{% endif %}
